CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    uri       varchar(255)                     NOT NULL,
    app       varchar(255)                     NOT NULL,
    ip        varchar(20)                     NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);